Add youtube icon and link.
YoshithaRathnayake/YoshithaRathnayake pull request #402
Opened 2024-01-14 21:34 UTC by ad-astra-per-ardua

## Purpose

The purpose of this Pull Request is to fix #397 

## Goals

Added youtube icon with link.

## Approach

### Screenshots

  
### Preview Link

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2024-01-14 21:34 UTC, ad-astra-per-ardua commented
Sorry for the delay.

2024-01-15 03:45 UTC, YoshithaRathnayake requested changes

2024-01-15 03:45 UTC, YoshithaRathnayake commented on README.md
> +<a href="https://www.youtube.com/channel/UCiuDD_uA4v5PF2cr-3nTChA"><img width="48" height="48" src="https://img.icons8.com/color/48/youtube-play.png" alt="Youtube Icon"/></a>
There is already given the size for the icon in the link so no need to add them manually right? @ad-astra-per-ardua 
What happened before you add the size? If there is no change by removing the width and the height remove them.

```suggestion
<a href="https://www.youtube.com/channel/UCiuDD_uA4v5PF2cr-3nTChA"><img src="https://img.icons8.com/color/48/youtube-play.png" alt="Youtube Icon"/></a>
```

2024-01-15 03:48 UTC, YoshithaRathnayake requested changes

2024-01-15 03:48 UTC, YoshithaRathnayake commented on README.md
> +<a href="https://www.youtube.com/channel/UCiuDD_uA4v5PF2cr-3nTChA"><img width="48" height="48" src="https://img.icons8.com/color/48/youtube-play.png" alt="Youtube Icon"/></a>
And for the youtube link, add the below link

https://www.youtube.com/@YoshithaRathnayake
```suggestion
<a href="https://www.youtube.com/@YoshithaRathnayake"><img width="48" height="48" src="https://img.icons8.com/color/48/youtube-play.png" alt="Youtube Icon"/></a>
```

Do not forget to subscribe my channel and follow my github account 😃

2024-01-15 04:13 UTC, YoshithaRathnayake requested changes

2024-01-15 04:13 UTC, YoshithaRathnayake commented on README.md
> +
Remove this extra line @ad-astra-per-ardua 
```suggestion
```

2024-01-15 04:15 UTC, YoshithaRathnayake requested changes

2024-01-15 04:15 UTC, YoshithaRathnayake commented on README.md
> +<a href="https://www.youtube.com/@YoshithaRathnayake"><img src="https://img.icons8.com/color/48/youtube-play.png" alt="Youtube Icon"/></a>
Add the title, do not remove it @ad-astra-per-ardua 
```suggestion
<a href="https://www.youtube.com/@YoshithaRathnayake"><img src="https://img.icons8.com/color/48/youtube-play.png" alt="YouTube Icon" title="YouTube"/></a>
```

2024-01-15 04:16 UTC, YoshithaRathnayake requested changes

2024-01-15 04:16 UTC, YoshithaRathnayake commented on README.md
> +<a href="https://www.youtube.com/@YoshithaRathnayake"><img src="https://img.icons8.com/color/48/youtube-play.png" alt="Youtube Icon"/></a>
```suggestion
<a href="https://www.youtube.com/@YoshithaRathnayake"><img src="https://img.icons8.com/color/48/youtube-play.png" alt="YouTube Icon"/></a>
```

2024-01-15 04:26 UTC, YoshithaRathnayake approved these changes
Good job!
Thank you @ad-astra-per-ardua 
Don't forget to subscribe my youtube channel and follow me on github and social media

2024-01-15 04:27 UTC, merged